# Generated by Django 3.0.9 on 2020-10-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nomeCompleto',
            new_name='Nome',
        ),
    ]
